### ISSUE TITLE
Include showIf option

### ISSUE THREAD

**Issue by awebdeveloper** [gwer/oncogene#10]
include a showIf option. This means only show the given question if the condition matches or callback returns true

**Comment by awebdeveloper** [comment]
This what i am planning to do 

1. step now has an option called skipIf which is a callback with config as a parameter
2. in getStepNode() 
    check if (callback is defined and the value of callback is false) then return false
3. in renderStep() 
    if getStepNode() is false call nextStep()

**Comment by gwer** [comment]
`getStepNode()` and `renderStep()` are only about rendering, no step logic. I'll think about it in the evening.
