### ISSUE TITLE
Support for multiple values

### ISSUE THREAD

**Issue by awebdeveloper** [gwer/oncogene#11]
Include support for multiple value section. 

eg:- what env do you support 
1. Browser
2. Node
3. Jasmine 
4.  jquery

Here i could select more than one. Also, allow me to decide if the key is array or object.

**Comment by gwer** [comment]
Can you show an example how you want to configure it?
The key is array or object? Are you sure?

**Comment by awebdeveloper** [comment]
look at this
http://eslint.org/docs/user-guide/configuring#specifying-environments

how do we do this in oncogene without having true/false for each option

**Comment by gwer** [comment]
I'm asking about step configuring. Looks like different step definition structure and different step view in interface.

**Comment by awebdeveloper** [comment]
I hope this is what you meant. 

```
    key: 'env',
    hint: 'You are developing for',
    multiple: true, 
    variants: [{
      code: 'Node',
      value: {"node":true}
    },
    {
      code: 'Browser',
      value: {"browser":true}
    },
    {
      code: 'Jasmine',
      value: {"jasmine":true}
    }]
```
Supported values of **multiple** are `false, true/array, object`

**Comment by awebdeveloper** [comment]
also how do i add to a array . Look at the switch case example below link

http://eslint.org/docs/rules/indent#switchcase

**Comment by gwer** [comment]
This requires changes in interfaces. There is a need to add checkboxes and apply button. This is new user experience. Should we add radio buttons and apply button to steps without multiply values? There is a need to keep interface consistency.

**Comment by awebdeveloper** [comment]
Yup makes perfect sense. I could help you with that if you want.

**Comment by gwer** [comment]
I'm all for it.

**Comment by awebdeveloper** [comment]
#12 and #16 does lay most of the base work needed. You could now build the UI for multiple
