### ISSUE TITLE
Integrate Pretier

### ISSUE THREAD

**Issue by awebdeveloper** [gwer/oncogene#19]
Prettier is an opinionated JavaScript code auto formatter.
https://github.com/prettier/prettier

I have pre-commit hook for that
https://github.com/awebdeveloper/pre-commit-prettier

**Comment by gwer** [comment]
I will integrate linter later, not autoformatter.

**Comment by awebdeveloper** [comment]
its being used by react

**Comment by gwer** [comment]
It doesn't mean that you should use this tool in every project. I prefer manual formatting.
