### ISSUE TITLE
Add support for callbacks

### ISSUE THREAD

**Issue by awebdeveloper** [gwer/oncogene#20]
Include support for following callback

1. onResult
2. onValueSelected

**Comment by gwer** [comment]
`onValueSelected` === `options.steps[].callback`

Oncogene is designed for one simple use case. But it allows you to expand its behaviour through inheritance ([see example](https://github.com/gwer/oncogene/blob/master/examples/stylelint.html#L51-L53)).

**Comment by awebdeveloper** [comment]
yes i know and i am doing it. But having handlers makes sense. 

Also from `onValueSelected` i mean `afterValueSelected`. Oncogene takes care of adding value to config and then i do my logic in callback

**Comment by gwer** [comment]
`options.steps[].callback` is calling after adding value to config.

If you need to call the same function after each step, you may either use `.map()` for steps or extend the functionality:
```
class MyOncogene extends Oncogene {
    nextStep() {
        super.nextStep()
        // Your code...
    }
}

new MyOncogene(options)
```

**Comment by awebdeveloper** [comment]
oh.... It wasn't obvious. Yes, map is a good way. 

Then can we add a onResult Callback
