### ISSUE TITLE
Steps validation

### ISSUE THREAD

**Issue by gwer** [gwer/oncogene#5]
There is a need to add validation for steps list.

**Comment by maximgatilin** [comment]
@gwer сan you explain more details? What kind of validation?

**Comment by gwer** [comment]
@maximgatilin, every step should contain:
- key OR/AND callback (callback should be a function),
- variants[] (with at least two items).

Every variant should contain:
- hint OR/AND code,
- value.

Current validations you can see [here](https://github.com/gwer/oncogene/blob/master/oncogene.js#L196-L218).

**Comment by maximgatilin** [comment]
I'm going to try resolve this issue on the weekends, can you assign it to me?

**Comment by gwer** [comment]
This is open source, of course you can (=
